name: 'Merge branches'
description: 'Marges two branches if base exists and sends slack notification if conflicts'
inputs:
  repository:
    description: 'The current repository'
    required: true
  git-token:
    required: true
  source-branch:
    description: 'Source branch for merge'
    required: true
  target-branch:
    description: 'Target branch for merge'
    required: true
  slack-user:
    description: 'User Slack id to tag in Slack message'
  slack-link:
    description: 'Slack Webhook link'
    required: true
  slack-channel:
    description: 'Slack channel name to receive notifications'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout current repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
    - name: Merge branches
      id: merge
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ inputs.git-token }}
        source_ref: ${{ inputs.source-branch }}
        target_branch: ${{ inputs.target-branch }}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
        
    - name: Sends a Slack Notification
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ steps.merge.outputs.status == 'failure' }}
        step: |
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: ${{ inputs.slack-channel }}
            SLACK_WEBHOOK: ${{ inputs.slack-link }}
            SLACK_LINK_NAMES: true
            SLACK_MESSAGE: 'Disregard this message. This is a test!'
            
      
      
